name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Tests
    uses: frappe/frappe/.github/workflows/_base-server-tests.yml@develop
    with:
      enable-postgres: true
      parallel-runs: 2
      disable-socketio: true
      disable-redis-socketio: true
